name: aec_venv
channels:
  - defaults
dependencies:
  - python=3.8
  - biopython=1.78
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - scikit-learn=1.3.0
  - scipy
  - pip:
      - pyqt5==5.15.9
      - pyqt5-sip==12.12.2
      - selenium==4.11.2

