# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
name: aec_venv
channels:
  - defaults
dependencies:
  - ca-certificates=2023.08.22
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.12
  - python=3.8
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - biopython=1.78
  - pandas
  - numpy
  - openpyxl
  - scipy
  - matplotlib
  - scikit-learn=1.3.0
  - pip
  - pip:
      - pyqt5==5.15.9
      - selenium==4.11.2

