# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
name: aec_venv
channels:
  - defaults
dependencies:
  - ca-certificates
  - libcxx
  - libffi
  - ncurses
  - openssl
  - python=3.8
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - biopython=1.78
  - pandas
  - numpy
  - openpyxl
  - scipy
  - matplotlib
  - scikit-learn=1.3.0
  - pip
  - pip:
      - pyqt5
      - selenium==4.11.2

